-- AlterTable
ALTER TABLE "clientes" ALTER COLUMN "a1-estc" SET DATA TYPE TEXT,
ALTER COLUMN "estado-entrega" SET DATA TYPE TEXT,
ALTER COLUMN "estado-cadastro" SET DATA TYPE TEXT,
ALTER COLUMN "a1-fatacum" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "ticket-medio" SET DATA TYPE DECIMAL(65,30);
